//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingManagementSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountingManagementSystemEntities : DbContext
    {
        public AccountingManagementSystemEntities()
            : base("name=AccountingManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<tblCompany> tblCompanies { get; set; }
        public DbSet<tblCostCenter> tblCostCenters { get; set; }
        public DbSet<tblCostElement> tblCostElements { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblDepartment> tblDepartments { get; set; }
        public DbSet<tblDesignation> tblDesignations { get; set; }
        public DbSet<tblDistrict> tblDistricts { get; set; }
        public DbSet<tblEmail> tblEmails { get; set; }
        public DbSet<tblExpense> tblExpenses { get; set; }
        public DbSet<tblItem> tblItems { get; set; }
        public DbSet<tblItemSize> tblItemSizes { get; set; }
        public DbSet<tblLogIn> tblLogIns { get; set; }
        public DbSet<tblMoneyReceived> tblMoneyReceiveds { get; set; }
        public DbSet<tblPacking> tblPackings { get; set; }
        public DbSet<tblPayment> tblPayments { get; set; }
        public DbSet<tblPost> tblPosts { get; set; }
        public DbSet<tblPurchaseDTL> tblPurchaseDTLs { get; set; }
        public DbSet<tblPurchaseHDR> tblPurchaseHDRs { get; set; }
        public DbSet<tblRecipient> tblRecipients { get; set; }
        public DbSet<tblSalesDTL> tblSalesDTLs { get; set; }
        public DbSet<tblSalesHDR> tblSalesHDRs { get; set; }
        public DbSet<tblSalesReturn> tblSalesReturns { get; set; }
        public DbSet<tblSupplier> tblSuppliers { get; set; }
        public DbSet<tblThana> tblThanas { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<tblVillage> tblVillages { get; set; }
        public DbSet<tblWeight> tblWeights { get; set; }
        public DbSet<tblStock> tblStocks { get; set; }
        public DbSet<tblSetting> tblSettings { get; set; }
    }
}
