//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingManagementSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public int Id { get; set; }
        public Nullable<bool> IsInvoiceHeaderVisible { get; set; }
        public Nullable<bool> IsSalesDiscount { get; set; }
        public Nullable<bool> IsFooterMoto { get; set; }
        public Nullable<bool> IsHeaderMoto { get; set; }
    }
}
